apiVersion: v1
kind: Service
metadata:
  name: teamcity-server
  label:
    app: teamcity
    app-part: server
spec:
  type: LoadBalancer
  selector:
    app: teamcity-server
  ports:
  - port: 80
    name: http
    targetPort: 8111
