apiVersion: v1
kind: Service
metadata:
  name: teamcity-pgsql
  labels:
    app: teamcity-pgsql
spec:
  type: ClusterIP
  selector:
    app: teamcity-pgsql
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
